// User Reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const LOADING_MESSAGES = 'LOADING_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';
export const MARK_CONVERSATIONS_READ = 'MARK_CONVERSATIONS_READ';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const SET_CONTACTS = 'SET_CONTACTS';

// UI Reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const LOADING_DATA = 'LOADING_DATA';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// Data Reducer types
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const POST_PRODUCT = 'POST_PRODUCT';
export const UPLOAD_IMAGE_PRODUCT = 'UPLOAD_IMAGE_PRODUCT';
export const LOADING_PIC = 'LOADING_PIC';
export const STOP_LOADING_PIC = 'STOP_LOADING_PIC';
export const RESET_PRODUCT = 'RESET_PRODUCT';
